microsocial/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from soft_user.views import LoginView, ConfirmRecoveryView, RecoveryView
from django.conf import settings
from profiles.views import SettingsView


urlpatterns = patterns(
    '',
    url(
        r'^$',
        'microsocial.views.root',
        name='root',
    ),
    url(
        r'^login/$',
        LoginView.as_view(),
        name='login',
    ),
    url(
        r'^logout/$',
        'django.contrib.auth.views.logout_then_login',
        name='logout',
    ),
    url(
        r'^profile/',
        include('profiles.urls'),
    ),
    url(
        r'^registration/',
        include('soft_user.urls'),
    ),
    url(
        r'^password-recovery/$',
        ConfirmRecoveryView.as_view(),
        name='confirm_recovery',
    ),
    url(
        r'^settings/$',
        SettingsView.as_view(),
        name='settings',
    ),
    url(
        r'^password-recovery/(?P<key>.+?)/$',
        RecoveryView.as_view(),
        name='password_recovery',
    ),
    url(
        r'^i18n/',
        include('django.conf.urls.i18n'),
    ),
    url(
        r'^admin/',
        include(admin.site.urls),
    ),

)

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
     url(
        r'',
        include('django.contrib.flatpages.urls'),
     ),
]

profiles/urls.py
from django.conf.urls import patterns, include, url
from .views import ProfileDetail


urlpatterns = patterns(
    '',
    url(
        r'^(?P<pk>\d+)/$',
        ProfileDetail.as_view(),
        name='profile'
    ),
)

profiles/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import Q
from django.db.transaction import atomic
from soft_user.models import SoftUser
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _
import os


def get_ids_from_profiles(*profiles):
    return [profiles.pk if isinstance(profile, Profile) else int(profile) for profile in profiles]


def make_avatar_fn(instance, filename):
    id_str = str(instance.pk)
    return 'avatars/{sub_dir}/{id}_{rnd}{ext}'.format(
        sub_dir=id_str.zfill(2)[-2:],
        id=id_str,
        rnd=get_random_string(8, 'abcdefghijklmnopqrstuvwxyz0123456789'),
        ext=os.path.splitext(filename)[1],
    )


class ProfileFriendShipManager(models.Manager):

    def are_friends(self, profile1, profile2):
        profile1_id, profile2_id = get_ids_from_profiles(profile1, profile2)
        return self.filter(pk=profile1_id, friends__pk=profile2_id).exists()

    @atomic
    def add(self, profile1, profile2):
        profile1_id, profile2_id = get_ids_from_profiles(profile1, profile2)
        if profile1_id == profile2_id:
            raise ValueError(_(u'Вы себе уже друг.'))
        if not self.are_friends(profile1, profile2):
            through_model = self.model.friends.through
            through_model.objects.bulk_create([
                through_model(from_profile_id=profile1_id, to_profile_id=profile2_id),
                through_model(from_profile_id=profile2_id, to_profile_id=profile1_id),
            ])
            FriendInvitation.objects.filter(
                Q(from_profile_id=profile1_id, to_profile_id=profile2_id) | Q(from_profile_id=profile2_id, to_profile_id=profile1_id)
            ).delete()
            return True

    def delete(self, profile1, profile2):
        profile1_id, profile2_id = get_ids_from_profiles(profile1, profile2)
        if self.are_friends(profile1, profile2):
            through_model = self.model.friends.through
            through_model.objects.filter(
                Q(from_profile_id=profile1_id, to_profile_id=profile2_id) | Q(from_profile_id=profile2_id, to_profile_id=profile1_id)
            ).delete()
            return True


class Profile(models.Model):
    user = models.OneToOneField(SoftUser, verbose_name=_(u'пользователь'), related_name='profile')
    city = models.CharField(verbose_name=_(u'город'), blank=True, max_length=50)
    company = models.CharField(verbose_name=_(u'компания'), blank=True, max_length=100)
    avatar = models.ImageField(_(u'изображение'), upload_to=make_avatar_fn, blank=True)
    friends = models.ManyToManyField('self', verbose_name=_(u'друзья'), symmetrical=True, blank=True)
    about = models.TextField(verbose_name=_(u'о себе'), blank=True)
    interests = models.TextField(verbose_name=_(u'интересы'), blank=True)

    friendship = ProfileFriendShipManager()

    class Meta:
        verbose_name = _(u'профиль')
        verbose_name_plural = _(u'профили')
        ordering = ('user',)

    def __unicode__(self):
        return "%s %s" % (self.user.first_name, self.user.last_name)


class FriendInvitationManager(models.Manager):
    def is_pending(self, from_profile, to_profile):
        from_profile_id, to_profile_id = get_ids_from_profiles(from_profile, to_profile)
        return self.filter(from_profile_id=from_profile_id, to_profile_id=to_profile_id).exists()

    def add(self, from_profile, to_profile):
        from_profile_id, to_profile_id = get_ids_from_profiles(from_profile, to_profile)
        if from_profile_id == to_profile_id:
            raise ValueError(_(u'Вы себе уже друг.'))
        if Profile.friendship.are_friends(from_profile_id, to_profile_id):
            raise ValueError(_(u'Вы уже друзья.'))
        if self.is_pending(from_profile_id, to_profile_id):
            raise ValueError(_(u'Заявка была создана и ожидает рассмотрения.'))
        if self.is_pending(to_profile_id, from_profile_id):
            Profile.friendship.add(from_profile_id, to_profile_id)
            return 2
        self.create(from_profile_id=from_profile_id, to_profile_id=to_profile_id)
        return 1

    def approve(self, from_profile, to_profile):
        from_profile_id, to_profile_id = get_ids_from_profiles(from_profile, to_profile)
        if not self.is_pending(from_profile_id, to_profile_id):
            raise ValueError(_(u'Заявка не существует.'))
        return Profile.friendship.add(from_profile_id, to_profile_id)

    def reject(self, from_profile, to_profile):
        from_profile_id, to_profile_id = get_ids_from_profiles(from_profile, to_profile)
        self.filter(from_profile_id=from_profile_id, to_profile_id=to_profile_id).delete()


class FriendInvitation(models.Model):
    from_profile = models.ForeignKey('profiles.Profile', related_name='outcoming_friend_invitations')
    to_profile = models.ForeignKey('profiles.Profile', related_name='incoming_friend_invitations')

    objects = FriendInvitationManager()

    class Meta:
        unique_together = ('from_profile', 'to_profile')

soft_user/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.core import validators
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _
# from django.core.signing import Signer, BadSignature, SignatureExpired
from django.core import signing


class SoftUserManager(BaseUserManager):
    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given username, email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)


class SoftUser(AbstractBaseUser, PermissionsMixin):
    NO_SEX = 0
    SEX_MALE = 1
    SEX_FEMALE = 2
    SEX_CHOICES = (
        (NO_SEX, ''),
        (SEX_MALE, _('men')),
        (SEX_FEMALE, _('women')),
    )
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    birth_date = models.DateField(_('birth date'), blank=True, null=True)
    sex = models.SmallIntegerField(_('sex'), choices=SEX_CHOICES, null=True, default=0)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin '
                                   'site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    confirmed_registration = models.BooleanField(_('confirmed registration'), default=False)

    objects = SoftUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)

    def create_confirm_link(self, salt):
        return reverse('confirm_registration', kwargs={'key': self.make_salt_key(salt)})

    def create_recovery_link(self, salt):
        return reverse('password_recovery', kwargs={'key': self.make_timestamp_salt_key(salt)})

    def make_salt_key(self, salt):
        return signing.Signer(salt).sign(self.id)

    def make_timestamp_salt_key(self, salt):
        return signing.dumps({"id": self.id, "last_login": str(self.last_login)}, salt=salt)

    @staticmethod
    def check_registration_key(salt, string):
        try:
            return signing.Signer(salt).unsign(string)
        except signing.BadSignature:
            return False

    @staticmethod
    def check_recovery_key(string, salt, max_age=0):
        try:
            return signing.loads(string, salt=salt, max_age=max_age)
        except signing.BadSignature, signing.SignatureExpired:
            return False

profiles/views.py
# -*- coding: utf-8 -*-
from django.contrib import messages
from django.contrib.auth import login, BACKEND_SESSION_KEY
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView
from .models import Profile
from posts.models import Post
from .forms import SettingsForm
from soft_user.models import SoftUser
from soft_user.forms import ChangePassForm, ChangeEmailForm


class ProfileDetail(TemplateView):
    model = Profile
    template_name = "profiles/profile.html"

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        self.user = get_object_or_404(SoftUser, pk=kwargs['pk'])
        return super(ProfileDetail, self).dispatch(request, *args, **kwargs)

    def get_wall_posts(self):
        paginator = Paginator(self.user.profile.wall_posts.select_related('created_by'), 20)
        page = self.request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)
        return posts

    def get_context_data(self, **kwargs):
        context = super(ProfileDetail, self).get_context_data(**kwargs)
        context['profile'] = self.user.profile
        context['posts'] = self.get_wall_posts()
        return context

    def post(self, request, *args, **kwargs):
        Post.objects.create(profile=Profile.objects.get(pk=kwargs['pk']), created_by=request.user.profile,
                            created_at=datetime.now(), text=request.POST['text'])
        self.object = Profile.objects.get(pk=kwargs['pk'])
        # context = self.get_context_data(**kwargs)
        # return self.render_to_response(context)
        return redirect(request.path)


class SettingsView(TemplateView):
    template_name = 'profiles/settings.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        action = request.POST.get('action')
        self.profile_form = SettingsForm(
            request.user,
            request.POST if action == 'profile' else None,
            request.FILES if action == 'profile' else None,
            initial={
                'first_name': request.user.first_name,
                'last_name': request.user.last_name,
                'birth_date': request.user.birth_date,
                'sex': request.user.sex,
                'city': request.user.profile.city,
                'company': request.user.profile.company,
                'about': request.user.profile.about,
                'interests': request.user.profile.interests,
                'avatar': request.user.profile.avatar,
        })
        self.form_pass_change = ChangePassForm(request.POST if action == 'pass' else None,
                                               user=request.user if action == 'pass' else None)
        self.form_email_change = ChangeEmailForm(request.POST if action == 'email' else None,
                                                 user=request.user)

        return super(SettingsView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SettingsView, self).get_context_data(**kwargs)
        context['profile_form'] = self.profile_form
        context['form_pass_change'] = self.form_pass_change
        context['form_email_change'] = self.form_email_change

        return context

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(form=self.profile_form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        if self.profile_form.is_valid():
            self.profile_form.save()
            messages.success(request, u'Профиль успешно сохранен.')
            return redirect(request.path)
        elif self.form_pass_change.is_valid():
            self.form_pass_change.save()
            request.user.backend = request.session[BACKEND_SESSION_KEY]
            login(request, request.user)
            messages.success(request, u'Пароль успешно изменен.')
            return redirect(request.path)
        elif self.form_email_change.is_valid():
            self.form_email_change.save()
            messages.success(request, u'Email успешно изменен.')
            return redirect(request.path)
        return self.get(request, *args, **kwargs)

profiles/templates/profiles/profile.html
{% extends 'base.html' %}

{% load staticfiles messages i18n show_posts %}

{% block dashboard %}
    <div class="col-sm-3">
        {% if profile.avatar %}
            <img class="img-responsive img-rounded" src="{{ profile.avatar.url }}" alt="avatar">
        {% else %}
            <img class="img-responsive img-rounded" src="{% static 'profile/no_avatar.jpg' %}" alt="no_avatar">
        {% endif %}
        {% if profile == user.profile %}
            <div class="text-center" style="margin-top: 10px;">
                <a class="text-primary" href="{% url 'settings' %}">{% trans 'настройки' %}</a>
            </div>
        {% endif %}
    </div>
    <div class="col-sm-9">
        {% block dashboard_general_message %}
            {% messages size=6 offset=3 %}
        {% endblock dashboard_general_message %}
        {% block dashboard_content %}
            <div class="row">
                <div class="col-sm-12">
                    <h2>{{ profile.user.last_name }} {{ profile.user.first_name }}</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <span>{% trans 'пол'|capfirst %}:</span>
                </div>
                <div class="col-sm-10">
                    <span>{{ profile.user.get_sex_display }}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <span>{% trans 'дата рождения'|capfirst %}:</span>
                </div>
                <div class="col-sm-10">
                    <span>{{ profile.user.birth_date }}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <span>{% trans 'город'|capfirst %}:</span>
                </div>
                <div class="col-sm-10">
                    <span>{{ profile.city }}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <span>{% trans 'место работы'|capfirst %}:</span>
                </div>
                <div class="col-sm-10">
                    <span>{{ profile.company }}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <span>{% trans 'о себе'|capfirst %}:</span>
                </div>
                <div class="col-sm-10">
                    <span>{{ profile.about }}</span>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2">
                    <span>{% trans 'интересы'|capfirst %}:</span>
                </div>
                <div class="col-sm-10">
                    <span>{{ profile.interests }}</span>
                </div>
            </div>
            <div class="row" style="margin: 20px 0;">
                <form role="form" method="post">
                {% csrf_token %}
                    <div class="form-group">
                        <textarea rows="4"  name="text" style="width: 90%;"></textarea>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="center-block btn btn-primary pull-left">
                            {% trans 'опубликовать'|capfirst %}
                        </button>
                    </div>
                    <input type="hidden" name="next" value=""/>
                </form>
            </div>
            {% show_posts posts %}
        {% endblock dashboard_content %}
    </div>
{% endblock dashboard %}

profiles/templates/profiles/settings.html
{% extends 'base.html' %}

{% load messages i18n show_posts staticfiles %}

{% block dashboard %}
    <div class="container-fluid">
        <div class="row">
            {% block dashboard_content %}
                <form role="form" enctype="multipart/form-data" method="post" class="form-horizontal">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="profile">
                    <div class="col-sm-3">
                        {% if profile_form.user.profile.avatar %}
                            <img class="img-responsive img-rounded"
                                 src="{{ profile_form.user.profile.avatar.url }}" alt="avatar">
                        {% else %}
                            <img class="img-responsive img-rounded"
                                 src="{% static 'profile/no_avatar.jpg' %}" alt="no avatar">
                        {% endif %}
                        <input name="avatar-clear" type="checkbox"> {% trans 'удалить' %}
                        <input id="id_avatar" name="avatar" type="file">
                    </div>
                    <div class="col-sm-9">
                        {% block dashboard_general_message %}
                            {% messages size=12 offset=0 %}
                        {% endblock dashboard_general_message %}
                        {% for field in profile_form %}
                            {% if field.name != 'avatar' %}
                                <div class="form-group">
                                    {% field_errors field.errors %}
                                    <label for="{{ field.id_for_label }}" class="col-sm-2 control-label">
                                        {{ field.label|capfirst }}
                                    </label>
                                    <div class="col-sm-4">
                                        {{ field }}
                                    </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                        <input type="hidden" name="next" value=""/>
                        <div class="form-group">
                            <div class="col-md-2"></div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-info" name="profile">
                                    {% trans 'сохранить'|capfirst %}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
                <form method="post" class="form-horizontal">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="pass">
                    <div class="col-sm-9 col-sm-offset-3">
                        <h3 class="col-sm-offset-2">{% trans 'изменение пароля'|upper %}</h3>
                        {% for field in form_pass_change %}
                            <div class="form-group">
                                <div class="col-sm-2"></div>
                                <div class="col-sm-4">
                                    {% field_errors field.errors %}
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <div class="col-md-2"></div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-info" name="pass">
                                    {% trans 'изменить'|capfirst %}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
                <form method="post" class="form-horizontal">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="email">
                    <div class="col-sm-9 col-sm-offset-3">
                        <h3 class="col-sm-offset-2">{% trans 'изменение email'|upper %}</h3>
                        <div class="form-group">
                            <div class="col-sm-2"></div>
                            <span class="col-sm-2">
                                {{ form_email_change.user.email }}
                            </span>
                        </div>
                        {% for field in form_email_change %}
                            <div class="form-group">
                                <div class="col-sm-2"></div>
                                <div class="col-sm-4">
                                    {% field_errors field.errors %}
                                    {{ field }}
                                </div>
                            </div>
                        {% endfor %}
                        <div class="form-group">
                            <div class="col-md-2"></div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-info" name="email">
                                    {% trans 'изменить'|capfirst %}
                                </button>
                            </div>
                        </div>
                    </div>
                </form>
            {% endblock dashboard_content %}
        </div>
    </div>

{% endblock dashboard %}